# Generated by Django 3.2.13 on 2022-04-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
